#+TITLE: Useful day to day links are uploaded here
#+AUTHOR: Dinesh A
#+DATE:
#+OPTIONS: toc:nil H:3 num:2
#+STARTUP: showeverything

*** Yasnippets org mode
    Here is a better folder for org mode in Emacs
    url = git@github.com:yyr/yasnippets-orgmode.git


*** Awesome html conversion.

    url = git@github.com:fniessen/org-html-themes.git

    - keep this line on top of the file
      #+SETUPFILE: /home/dinesh/softwares/org-html-themes/setup/theme-bigblow.setup


*** Install Emacs 25.1

    Stable versions (25.1 currently):

    - sudo apt-add-repository -y ppa:adrozdoff/emacs
    - sudo apt update
    - sudo apt install emacs25
    - Provided packages for LTS 14.04 and 16.04.

*** Unusual installation behavious
    - do M-x package refresh.
    - And install.



*** Install Dropbox.

*** Install latex


*** Emacs snapshot version is 26.0.50


*** Citing in org-ref

    Citing is easy.
**** Using doi
     - Say you have a DOI of a paper.
     - do M-x doi-add-bibtex-entry
     - It will automatically add the paper. And will download if it is allowed.

**** Using cross ref
     - Say we have a title or author or journal of a paper.
     - Then do, M-x cross-ref-add-bibtex-entry
     - Paste the title or what ever.
     - org-ref will search for our paper and gives few suggestions.
     - Enter on requisite paper.
     - If you want more then mark all those papers and enter. C-spc.

*** Notes creation from bib file.

**** from bib file
     Once the bib file is created. We can do
     - do M-x org-ref-open-bibtex-notes.
     - It will create a heading named after your file. With citing
       your bib. And other contents.
     - Since it is citing your file. Org-ref has awesome functions for
       clickable citations.
     - you can go to the link of the citation. Or you can download the pdf
       from web and many more.
     - Say, while entering the bib using crossref or doi, our system
       didn't download the pdf.
     - Since in clickable link we have a download option it will download
       it if available.
     - If our institute is not allowing so. Then we can manually
       download the pdf.
     - And don't forget to save it in your default papers storage directory.
     - And save it as the name as it was cited.



**** Evil key bindings.
     - (evil-leader/set-key "p" 'org-ref-open-pdf-at-point)
     - (evil-leader/set-key "o" 'org-ref-open-bibtex-notes)


*** Screen resolution ubuntu fix
    - xrandr -s 1366x768

*** John Kitchin website links
    - pip install pycse


*** Bashrc configuration

    #+BEGIN_SRC sh
      # Enable tab completion
      source ~/git-completion.bash
      # export PATH="$HOME/miniconda3/bin:$PATH"
      # colors!
      green="\[\033[0;32m\]"
      blue="\[\033[0;34m\]"
      purple="\[\033[0;35m\]"
      reset="\[\033[0m\]"

      # Change command prompt
      source ~/git-prompt.sh
      export GIT_PS1_SHOWDIRTYSTATE=1
      # '\u' adds the name of the current user to the prompt
      # '\$(__git_ps1)' adds git-related stuff
      # '\W' adds the name of the current directory
      export PS1="$purple\u$green\$(__git_ps1)$blue \W $ $reset"
      PATH=/usr/racket/bin:$PATH
      # export PATH="~/.cargo/bin:$PATH"
      # export PATH="/home/dinesh/.cask/bin:$PATH"
      # export PATH="/home/dinesh/.edm/envs/edm/bin:$PATH"
      bind '"\e[A": history-search-backward'
      bind '"\e[B": history-search-forward'

      alias ..="cd .."
      alias ...="cd ..."
      alias sl="ls"
      alias l="ls"
      alias s="ls"
      alias p="pysph view"

      # added by Miniconda3 4.1.11 installer
      export PATH="/home/dinesh/anaconda2/bin:$PATH"
      # export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      export PATH="/home/dinesh/blender-2.78c-linux-glibc219-x86_64:$PATH"
      export PATH="/home/dinesh/.edm/envs/edm/bin:$PATH"
    #+END_SRC


    This file depends on two files
    - ~/git-completion.bash
    - ~/git-prompt.sh

    Which could be found in this directory including bashrc

** Dropbox
   cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
   ~/.dropbox-dist/dropboxd

** Caps to ctrl key
    https://askubuntu.com/questions/412576/swap-caps-lock-and-ctrl-in-ubuntu-13-10
    - sudo apt-get install gnome-tweak-tool
